/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SparePartsImport } from './routes/spare-parts'
import { Route as LogisticsAndStorageImport } from './routes/logistics-and-storage'
import { Route as HdUsedMachinesImport } from './routes/hd-used-machines'
import { Route as ContactUsImport } from './routes/contact-us'
import { Route as AboutUsImport } from './routes/about-us'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SparePartsRoute = SparePartsImport.update({
  id: '/spare-parts',
  path: '/spare-parts',
  getParentRoute: () => rootRoute,
} as any)

const LogisticsAndStorageRoute = LogisticsAndStorageImport.update({
  id: '/logistics-and-storage',
  path: '/logistics-and-storage',
  getParentRoute: () => rootRoute,
} as any)

const HdUsedMachinesRoute = HdUsedMachinesImport.update({
  id: '/hd-used-machines',
  path: '/hd-used-machines',
  getParentRoute: () => rootRoute,
} as any)

const ContactUsRoute = ContactUsImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRoute,
} as any)

const AboutUsRoute = AboutUsImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsImport
      parentRoute: typeof rootRoute
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsImport
      parentRoute: typeof rootRoute
    }
    '/hd-used-machines': {
      id: '/hd-used-machines'
      path: '/hd-used-machines'
      fullPath: '/hd-used-machines'
      preLoaderRoute: typeof HdUsedMachinesImport
      parentRoute: typeof rootRoute
    }
    '/logistics-and-storage': {
      id: '/logistics-and-storage'
      path: '/logistics-and-storage'
      fullPath: '/logistics-and-storage'
      preLoaderRoute: typeof LogisticsAndStorageImport
      parentRoute: typeof rootRoute
    }
    '/spare-parts': {
      id: '/spare-parts'
      path: '/spare-parts'
      fullPath: '/spare-parts'
      preLoaderRoute: typeof SparePartsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/hd-used-machines': typeof HdUsedMachinesRoute
  '/logistics-and-storage': typeof LogisticsAndStorageRoute
  '/spare-parts': typeof SparePartsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/hd-used-machines': typeof HdUsedMachinesRoute
  '/logistics-and-storage': typeof LogisticsAndStorageRoute
  '/spare-parts': typeof SparePartsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/hd-used-machines': typeof HdUsedMachinesRoute
  '/logistics-and-storage': typeof LogisticsAndStorageRoute
  '/spare-parts': typeof SparePartsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/hd-used-machines'
    | '/logistics-and-storage'
    | '/spare-parts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/hd-used-machines'
    | '/logistics-and-storage'
    | '/spare-parts'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/hd-used-machines'
    | '/logistics-and-storage'
    | '/spare-parts'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactUsRoute: typeof ContactUsRoute
  HdUsedMachinesRoute: typeof HdUsedMachinesRoute
  LogisticsAndStorageRoute: typeof LogisticsAndStorageRoute
  SparePartsRoute: typeof SparePartsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactUsRoute: ContactUsRoute,
  HdUsedMachinesRoute: HdUsedMachinesRoute,
  LogisticsAndStorageRoute: LogisticsAndStorageRoute,
  SparePartsRoute: SparePartsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about-us",
        "/contact-us",
        "/hd-used-machines",
        "/logistics-and-storage",
        "/spare-parts"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about-us": {
      "filePath": "about-us.tsx"
    },
    "/contact-us": {
      "filePath": "contact-us.tsx"
    },
    "/hd-used-machines": {
      "filePath": "hd-used-machines.tsx"
    },
    "/logistics-and-storage": {
      "filePath": "logistics-and-storage.tsx"
    },
    "/spare-parts": {
      "filePath": "spare-parts.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
